# @format

BOT:
  OWNERS: ["1212431696381612132","940959891005243442"]
  ADMINS: ["1212431696381612132","940959891005243442"]



LINKS:
  SUPPORT: "https://discord.gg/nexhq"
  MONGO_URI: ""
  VOTING: ""

SPOTIFY:
  ID: ""
  SECRET: ""

MANAGER:
  OWNERS: ["940959891005243442"]
  TOKEN: ""

NEX:
  PREFIX: "."
  EMOJIS: "black"
  COLOR: "FFC0CB"
  SHARDS: auto
  PER_CLUSTER: 1
  TOKEN: ""
  VOTEURI: "https://top.gg/bot/1272058924547178581/vote"
  TOPGGAUTH: ""

# JINGLE:
#   PREFIX: "?"
#   EMOJIS: "black"
#   COLOR: "#555555"
#   SHARDS: "auto"
#   PER_CLUSTER: 2
#   TOKEN: "MTE5MTk0NzUzMDIyNTg0ODQwMA.GN225m.gFvFBNCULOZENl46RxJgNukn6-THCXF2xdXuGU" #"MTE5MTk0NzUzMDIyNTg0ODQwMA.GWI-50.lTnUrFEbkfNpjXp7fHrDutAxejX6f2GqxtqaAM"
#   TOPGGAUTH: ""
#   VOTEURI: ""
  
# KYOKO:
#   PREFIX: "&"
#   EMOJIS: "black"
#   COLOR: "#548fc1"
#   SHARDS: "auto"
#   PER_CLUSTER: 2
#   TOKEN: "MTI1Mjk1ODQ4NDU4OTQ0OTI1Nw.GY0298.Znkpp5rvvdO07PTdVpWXj5xQZ2VchR0f2DnnBo"
#   TOPGGAUTH: ""

WEBHOOKS:
  ERROR: ""
  STATIC: ""
  PLAYER: ""
  SERVER: ""
  COMMAND: ""
